# Generated by Django 4.1.5 on 2023-01-26 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpayorder',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.address'),
        ),
        migrations.AddField(
            model_name='razorpayorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.cart'),
        ),
        migrations.AddField(
            model_name='razorpayorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pv_data',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.address'),
        ),
        migrations.AddField(
            model_name='orders',
            name='razorpaytransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.razorpaytransaction'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='wallet_transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.wallettransaction'),
        ),
        migrations.AddField(
            model_name='orderitemvariant',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.orders'),
        ),
        migrations.AddField(
            model_name='orderitemvariant',
            name='orderitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.orderitems'),
        ),
        migrations.AddField(
            model_name='orderitemvariant',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.orders'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct', to='vendor_app.product'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.store'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mlmadmin',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mlm',
            name='left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mlm',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mlm',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mlm',
            name='right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='level_plan_sponsors',
            name='sponsors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='level_plan_referrals',
            name='level_plan_referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.level_plan_referrals'),
        ),
        migrations.AddField(
            model_name='level_plan_referrals',
            name='level_plan_sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.level_plan_sponsors'),
        ),
        migrations.AddField(
            model_name='level_plan_referrals',
            name='referrals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gst_log',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.orderitems'),
        ),
    ]
