# Generated by Django 4.1.5 on 2023-12-30 21:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendordocs",
            name="vendor_idproof_doc_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendordocs",
            name="return_policy",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendordocs",
            name="shiping_policy",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendordocs",
            name="vendor_idproof",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
